from pathlib import Path
import json,html,re
root=Path(__file__).resolve().parents[1]
entries=json.loads((root/'resources/playlist-manifest.json').read_text())
esc=html.escape
svg_style='<style>text{font-family:Arial,sans-serif;fill:#17263e;font-size:17px}.small{font-size:14px}.title{font-size:22px;font-weight:700}.step{fill:#254fdb;font-size:14px;font-weight:700}</style>'
def svg(label,body):return '<svg role="img" aria-label="'+esc(label)+'" viewBox="0 0 800 330" xmlns="http://www.w3.org/2000/svg">'+svg_style+'<rect width="800" height="330" rx="12" fill="#fff"/>'+body+'</svg>'
layer=svg('Schematic section showing devices below stacked metal layers and a via between layers.', '''<text class="title" x="30" y="40">An IC is built in layers</text><rect x="60" y="246" width="680" height="45" fill="#dfe6f2"/><text x="85" y="275">Silicon substrate</text><rect x="100" y="208" width="170" height="38" fill="#a8b9d9"/><rect x="505" y="208" width="170" height="38" fill="#a8b9d9"/><text x="130" y="233">Devices</text><text x="535" y="233">Devices</text><rect x="60" y="172" width="680" height="18" fill="#8db3ef"/><text x="70" y="160">Metal 1</text><rect x="385" y="103" width="30" height="69" fill="#b993ee"/><text x="434" y="142">Via</text><rect x="60" y="85" width="680" height="18" fill="#254fdb"/><text x="70" y="76">Metal 2</text><text class="small" x="30" y="318">Schematic only; not a process cross-section or a scale drawing.</text>''')
photo=svg('Five stages of the positive-photoresist example: coating, exposure, development, etching and resist removal.', '''<text class="title" x="28" y="36">Pattern transfer in the lecture</text><g><rect x="28" y="58" width="226" height="105" rx="8" fill="#edf2ff"/><text class="step" x="43" y="82">1 · COAT &amp; BAKE</text><rect x="45" y="106" width="190" height="10" fill="#ae87dd"/><rect x="45" y="116" width="190" height="11" fill="#73a5d8"/><rect x="45" y="127" width="190" height="17" fill="#d9e1ed"/></g><g><rect x="286" y="58" width="226" height="105" rx="8" fill="#edf2ff"/><text class="step" x="302" y="82">2 · EXPOSE THROUGH MASK</text><rect x="306" y="98" width="55" height="8" fill="#17263e"/><rect x="433" y="98" width="55" height="8" fill="#17263e"/><path d="M380 96v27m18-27v27m18-27v27" stroke="#d39417" stroke-width="4"/><rect x="306" y="127" width="182" height="16" fill="#ae87dd"/></g><g><rect x="544" y="58" width="226" height="105" rx="8" fill="#edf2ff"/><text class="step" x="560" y="82">3 · DEVELOP</text><rect x="560" y="128" width="193" height="16" fill="#73a5d8"/><rect x="560" y="108" width="56" height="20" fill="#ae87dd"/><rect x="697" y="108" width="56" height="20" fill="#ae87dd"/></g><g><rect x="155" y="187" width="226" height="105" rx="8" fill="#edf2ff"/><text class="step" x="171" y="211">4 · ETCH THE FILM</text><rect x="171" y="231" width="55" height="26" fill="#ae87dd"/><rect x="309" y="231" width="55" height="26" fill="#ae87dd"/><rect x="171" y="257" width="55" height="12" fill="#73a5d8"/><rect x="309" y="257" width="55" height="12" fill="#73a5d8"/></g><g><rect x="415" y="187" width="226" height="105" rx="8" fill="#edf2ff"/><text class="step" x="431" y="211">5 · REMOVE RESIST</text><rect x="431" y="239" width="54" height="12" fill="#73a5d8"/><rect x="569" y="239" width="55" height="12" fill="#73a5d8"/><rect x="431" y="251" width="193" height="18" fill="#d9e1ed"/></g><text class="small" x="28" y="318">Purple: resist · Blue: deposited film · Gray: substrate</text>''')
eco=svg('Fabless design and foundry fabrication exchange layout and PDK information; an IDM performs both roles.', '''<text class="title" x="28" y="38">Design and fabrication are connected</text><rect x="45" y="90" width="260" height="92" rx="10" fill="#edf2ff"/><text x="93" y="126">Fabless design</text><text class="small" x="94" y="153">Defines the circuit</text><rect x="495" y="90" width="260" height="92" rx="10" fill="#e5f5ee"/><text x="571" y="126">Foundry</text><text class="small" x="535" y="153">Fabricates the circuit</text><path d="M313 112h169l-11-7m11 7-11 7" fill="none" stroke="#254fdb" stroke-width="3"/><text class="small" x="377" y="98">Layout</text><path d="M484 166H314l11-7m-11 7 11 7" fill="none" stroke="#147457" stroke-width="3"/><text class="small" x="357" y="193">PDK and rules</text><rect x="160" y="230" width="480" height="65" rx="10" fill="#f1ecfa"/><text x="207" y="258">Integrated device manufacturer</text><text class="small" x="260" y="281">Design + fabrication in one company</text>''')
blocks=[('3:22',202,'Historical perspective','Connecting separate components becomes costly and difficult as circuits grow. Integration forms many components on one silicon substrate.'),('8:20',500,'Scaling','The lecture introduces Moore’s prediction and explains why shrinking devices increases integration while making design more complex.'),('12:07',727,'Structure','Devices lie below interconnect layers. Different wiring planes allow connections that would otherwise cross and short.'),('21:09',1269,'Photolithography','A mask controls light exposure. Development, etching and resist removal transfer its pattern to the film; repeated use enables copying.'),('29:06',1746,'Fabrication terms','The lecture distinguishes ingot, wafer, die and packaged chip, and introduces yield as the proportion of good dies.'),('37:00',2220,'Industry roles','Design specifies the circuit; fabrication produces it. Fabless firms, foundries and IDMs organize these roles differently. PDKs communicate process information and rules.')]
notes=''.join('<section class="note-block"><a class="stamp" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=9QgdNsl9qwk&amp;t='+str(sec)+'s">'+time+' ↗</a><div><h2>'+title+'</h2><p>'+text+'</p></div></section>' for time,sec,title,text in blocks)
notes+='<h2>Lecture-based diagrams</h2><p class="muted">Redrawn from the explanation; these are not screenshots of the instructor’s slides.</p>'
for drawing,caption,t in [(layer,'Structure, 13:31–16:02',811),(photo,'Photolithography, 23:30–28:56',1410),(eco,'Industry roles, 42:14–47:37',2534)]:notes+='<figure>'+drawing+'<figcaption><a href="https://www.youtube.com/watch?v=9QgdNsl9qwk&amp;t='+str(t)+'s" target="_blank" rel="noopener">'+caption+' ↗</a></figcaption></figure>'
nav=[];pages=[]
for e in entries:
 n=e['position'];pid='video-'+str(n).zfill(2);title=esc(e['title']);source=e['source_level'];status={'transcript':'Transcript summary','description':'Description overview','title-only':'Notes pending'}[source]
 nav.append(f'<a href="#{pid}" data-page="{pid}"><span class="number">{n:02}</span><span>{title}<small>{status}</small></span><span class="nav-check"></span></a>')
 cover=f'<figure class="cover"><a href="{esc(e["url"])}" target="_blank" rel="noopener"><img src="{esc(e["thumbnail"])}" alt="YouTube thumbnail for {title}" width="336" height="188" loading="lazy"></a><figcaption>Thumbnail from this playlist · <a href="{esc(e["url"])}" target="_blank" rel="noopener">Watch video ↗</a></figcaption></figure>'
 if source=='transcript':body='<div class="source-label">Based on the retrieved timestamped transcript</div>'+notes
 elif source=='description':body='<div class="source-label">Paraphrased from this video’s description</div><p>'+esc(e['overview'])+'</p><div class="pending"><strong>Detailed notes are pending.</strong><p>The full transcript was not retrieved. This short overview does not cover the complete lecture.</p></div>'
 else:body='<div class="pending"><strong>Lecture content has not been verified.</strong><p>The video title and position are confirmed from the playlist. Open the source video; no lesson text, examples or diagrams have been inferred from its title.</p></div>'
 prev=f'<a href="#video-{n-1:02}">← Previous video</a>' if n>1 else '<span></span>';nxt=f'<a href="#video-{n+1:02}">Next video →</a>' if n<56 else ''
 pages.append(f'<article class="page" id="{pid}"'+('' if n==2 else ' hidden')+f'><div class="eyebrow">PLAYLIST POSITION {n:02} / 56</div><h1 tabindex="-1">{title}</h1>{cover}<div class="prose">{body}</div><div class="finish"><div><strong>Finished watching?</strong><p>This records viewing progress, not mastery.</p></div><button class="complete" data-complete="{pid}">Mark watched</button></div><div class="page-nav">{prev}{nxt}</div></article>')
css=(root/'tools/learning.css').read_text()+'''\nnav a small{display:block;font-size:12px;font-weight:400;opacity:.8;margin-top:4px}.cover{margin:24px 0;max-width:460px}.cover img{display:block;width:100%;height:auto;border-radius:12px;background:var(--line)}figcaption{font-size:13px;color:var(--muted);margin-top:8px}figure{margin:24px 0}.prose figure svg{width:100%;height:auto;display:block;border:1px solid var(--line);border-radius:12px}.source-label{font-size:13px;color:var(--green);font-weight:700;margin:25px 0 10px}.pending{background:var(--paper);border:1px solid var(--line);border-radius:12px;padding:24px;margin-top:24px}.pending p,.muted{color:var(--muted);font-size:15px}.note-block{display:grid;grid-template-columns:80px 1fr;gap:15px;margin:24px 0}.note-block h2{border:0;padding:0;margin:0 0 8px;font-size:22px}.note-block p{margin:0}.stamp{font:14px/1.6 monospace;padding-top:4px}.source-status{background:var(--paper);border:1px solid var(--line);border-radius:10px;padding:15px 18px;font-size:14px;color:var(--muted);margin-bottom:20px}.source-status strong{color:var(--ink)}@media(max-width:600px){.note-block{grid-template-columns:1fr;gap:4px}.cover{max-width:100%}}'''
js='''(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const key='vardhan-playlist-only-v1';let state={watched:[],theme:'light'};try{const s=JSON.parse(localStorage.getItem(key));if(s){state.watched=Array.isArray(s.watched)?s.watched:[];state.theme=s.theme==='dark'?'dark':'light';}}catch{}const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{$('#storage-note').hidden=false;}};function paint(){document.body.classList.toggle('dark',state.theme==='dark');$('#theme').textContent=state.theme==='dark'?'Light mode':'Dark mode';const valid=$$('.complete').filter(b=>state.watched.includes(b.dataset.complete));$('#progress-count').textContent=valid.length+' / 56 watched';$('#progress').value=valid.length;$$('.complete').forEach(b=>{let yes=state.watched.includes(b.dataset.complete);b.textContent=yes?'✓ Watched · Undo':'Mark watched';b.setAttribute('aria-pressed',String(yes));});$$('nav a').forEach(a=>a.querySelector('.nav-check').textContent=state.watched.includes(a.dataset.page)?'✓':'');}let first=true;function open(){let page=document.getElementById(location.hash.slice(1));if(!page?.classList.contains('page'))page=$('#video-02');$$('.page').forEach(p=>p.hidden=p!==page);$$('nav a').forEach(a=>{if(a.dataset.page===page.id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=page.querySelector('h1').textContent+' — VLSI Learning Vardhan';document.body.classList.remove('nav-open');$('#menu').setAttribute('aria-expanded','false');window.scrollTo(0,0);if(!first)page.querySelector('h1').focus({preventScroll:true});first=false;}$('#search').addEventListener('input',e=>{let q=e.target.value.trim().toLowerCase(),n=0;$$('nav a').forEach(a=>{let show=!q||document.getElementById(a.dataset.page).textContent.toLowerCase().includes(q);a.hidden=!show;if(show)n++;});$('#search-status').textContent=q?n+' matching entries':'';});$$('.complete').forEach(b=>b.addEventListener('click',()=>{let id=b.dataset.complete;state.watched=state.watched.includes(id)?state.watched.filter(x=>x!==id):[...state.watched,id];save();paint();}));$('#theme').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';save();paint();});$('#print').addEventListener('click',()=>window.print());$('#menu').addEventListener('click',()=>{$('#menu').setAttribute('aria-expanded',String(document.body.classList.toggle('nav-open')));});document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('nav-open');$('#menu').setAttribute('aria-expanded','false');}});window.addEventListener('hashchange',open);paint();open();})();'''
(root/'tools/playlist.js').write_text(js+'\n')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A source-limited VLSI playlist reader with 56 ordered videos, verified source status, lecture thumbnails and timestamped first-lecture notes."><title>VLSI Learning Vardhan — Playlist edition</title><style>'''+css+'''</style></head><body><a class="skip" href="#main">Skip to lesson</a><header class="topbar"><button id="menu" aria-label="Toggle playlist navigation" aria-controls="sidebar" aria-expanded="false">☰</button><a class="brand" href="#video-02"><span class="brand-icon">V</span><span>VLSI LEARNING<small>VARDHAN · PLAYLIST EDITION</small></span></a><div class="top-actions"><button id="theme">Dark mode</button><button id="print">Print entry</button></div></header><aside id="sidebar"><div class="sidebar-intro"><span class="eyebrow">THE ORIGINAL PLAYLIST</span><h2>Follow each video.</h2><label for="search">Find a video or topic</label><input id="search" type="search" placeholder="Try Verilog, timing, routing…"><p id="search-status" aria-live="polite"></p><div class="progress-label"><strong id="progress-count">0 / 56 watched</strong><span>Browser-local</span></div><progress id="progress" max="56" value="0"></progress></div><nav aria-label="Playlist videos">'''+''.join(nav)+'''</nav><div class="sidebar-note"><a href="https://www.youtube.com/playlist?list=PL4PtpyzWn6WbpzsiququkQV8Wqa_LzaqR" target="_blank" rel="noopener">Open the original playlist ↗</a><p>Order checked 9 September 2026. Position numbers include tutorials, the introduction and the live session.</p></div></aside><main id="main"><div class="source-status"><strong>Source-limited edition · Detailed notes are incomplete.</strong><br>56 playlist entries · 1 transcript summary · 34 description overviews · 21 entries awaiting lesson content. This reader contains no added exercises or capstones.</div><div id="storage-note" hidden role="status">Progress could not be saved. It will last for this session only.</div>'''+''.join(pages)+'''<footer>Lecture material: Prof. Sneh Saurabh, IIIT Delhi / NPTEL.<br>Only the supplied playlist is used for lesson content. Images are playlist thumbnails and explicitly identified redrawings. Videos and thumbnails require internet; the diagrams and available notes are embedded.</footer></main><noscript><style>.page[hidden]{display:block!important}#sidebar{position:static;width:auto;display:block}main{margin-left:0}.topbar{position:static}</style></noscript><script>'''+js+'''</script></body></html>'''
(root/'index.html').write_text(page)
print('Built',len(entries),'playlist entries with 56 thumbnail images and 3 source-grounded SVG diagrams.')
